#include<stdio.h>
#include<conio.h>
main()
{
  clrscr();
  int a,b,c,d,e,f,g;
  a=10;
  b=5;
  c=a+b;
  d=a-b;
  e=a*b;
  f=a/b;
  g=a%b;
  printf("a+b=%d",c);
  printf("\na-b=%d",d);
  printf("\na*b=%d",e);
  printf("\na/b=%d",f);
  printf("\na%%b=%d",g);
  getch();
  }